version: '3.3'

volumes:
  pg_data:
  static:
  docs:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./yatube_api/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - docs:/app/static

  nginx:
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
    ports:
      - "9500:80"
    volumes:
      - static:/backend_static
      - docs:/static
